### PR TITLE
Add support for OTLP HTTP Exporter

### PR DESCRIPTION
**Pull request by Djiit**
Hey, 
this PR:
- use the newer, recommended `-trace-` exporters
- allow the use of the http exporter when a `http://`url is provided

Test are passing, but I'm not sure how to test it live on an existing repo. Any help is appreciated :)

### CODE REVIEW

**Comment by Djiit** [comment]
Current version is not ideal as it ask the user to install its own exporter. Could this package provide its own version (dependencies instead of peerDependencies ?) Considering these are small packages, it would be easier for the users.

**Comment by Djiit** [comment]
Working :D
image

**Comment by Djiit** [comment]
Hey @gibsonjoshua55, did you had any chance to review this ? Thanks 🙇

**Review by gibsonjoshua55 — APPROVED** [review]
Hey @Djiit,

Thanks for the PR! This looks great!

Regarding your question about `peerDependencies` vs `dependencies`, I think I still side on leaving them `peerDependencies`.  I would imagine it's pretty common that people who use this project will like use `opentelemetry` packages elsewhere in their monorepo. I'd love to avoid creating dependency conflicts for them. Leaving these packages as peer dependencies allows each user to determine the exact versions they are using in their project.

I'm definitely open to more discussion on that point though! If you want discuss that more, feel free to open separate issue.

**Review by gibsonjoshua55 — CHANGES_REQUESTED** [review]
@Djiit, sorry for approving the PR and then following up with this comment, but I'm actually gonna request that we slightly change how we would indicate whether to use the HTTP vs GRPC exporter.

Looking at docs for the OTLP exporter, `http://` appears to be a valid url for both GRPC and HTTP exports. See the [OpenTelemetry Protocol Exporter Docs here](https://opentelemetry.io/docs/reference/specification/protocol/exporter/#configuration-options).

Instead of determining the protocol based on the URL structure, could we add it as option to the runner? Something like

```
"otel": {
    "runner": "@nxpansion/opentelemetry-nx-runner",
    "options": {
    "wrappedTasksRunner": "@nrwl/workspace/tasks-runners/default",
    "wrappedTasksRunnerOptions": {
        "cacheableOperations": ["build", "lint", "test", "e2e"]
    },
    "exporter": "otlp-grpc",
    "otlpOptions": {
        "url": "http://localhost:4317"
    }
    }
}
```
vs
```
"otel": {
    "runner": "@nxpansion/opentelemetry-nx-runner",
    "options": {
    "wrappedTasksRunner": "@nrwl/workspace/tasks-runners/default",
    "wrappedTasksRunnerOptions": {
        "cacheableOperations": ["build", "lint", "test", "e2e"]
    },
    "exporter": "otlp-http",
    "otlpOptions": {
        "url": "http://localhost:4318"
    }
    }
}
```

This way we wouldn't have to rely on making inferences based on the url protocol, which might imply either package being used.  

Thoughts?  I'd be happy to add to this PR to make this change. Or I could leave it up to you. Whatever works best!

**Comment by Djiit** [comment]
Fine by me :) I'll do it now

**Comment by Djiit** [comment]
I just pushed another version. Feel free to amend anything and merge :). I'll open a separate issue to discuss dependencies

**Review by gibsonjoshua55 — APPROVED** [review]

**Comment by gibsonjoshua55** [comment]
Thanks for the update @Djiit.  I'm away from my computer right now through the rest of the day, but I'll merge this when I'm back home tomorrow.

Once we get the peer dependency issue resolved (Issue #5 ), I'll publish a new version!

**Pull request merged**
